name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Lint with ruff
      run: poetry run ruff check my_ci_project/

    - name: Test with pytest and coverage
      run: poetry run pytest --cov=my_ci_project tests/ --cov-report=term-missing

    - name: Build package
      run: poetry build
